apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- deployment.yaml
- service.yaml
replicas:
- name: vote
  count: 1
images:
- name: schoolofdevops/vote
  newName: dopsdemo/vote
  newTag: main-f1d6230f-1619798232 # {"$imagepolicy": "instavote:vote:tag"}
namespace: instavote
commonLabels:
  project: instavote
  env: staging
commonAnnotations:
  supported-by: "sre@example.com"
